Report Finished

diff --git a/assignment-1/Makefile b/assignment-1/Makefile
--- a/assignment-1/Makefile
+++ b/assignment-1/Makefile
@@ -24,11 +24,11 @@ RELEASE_FLAGS = -Wall -Wextra -std=c++11 -O2 -DNDEBUG
 $(BIN_DIR):
 	mkdir -p $(BIN_DIR)
 
-# Debug build
+# Debug build (make debug)
 debug: CXXFLAGS = $(DEBUG_FLAGS)
 debug: $(TARGET)
 
-# Release build
+# Release build (make / make release)
 release: CXXFLAGS = $(RELEASE_FLAGS)
 release: $(TARGET)
 
@@ -40,6 +40,22 @@ $(BIN_DIR)/assignment-1: $(OBJS) | $(BIN_DIR)
 $(BIN_DIR)/%.o: $(SRC_DIR)/%.cpp | $(BIN_DIR)
 	$(CXX) $(CXXFLAGS) -c $< -o $@ -I$(INC_DIR)
 
-# Clean up
-clean:
+
+# Check that no unwanted libraries are included (make check_headers)
+check_headers: 
+	@echo "Checking for disallowed headers..."
+	@if grep -R "include" $(SRC_DIR) | \
+		grep -v -e "boost/" -e "<iostream>" -e "<vector>" -e "<string>" -e "<fstream>" -e "<stdexcept>" -e "<cassert>" -e "<cmath>" \
+		-e "<cstdlib>" -e "<chrono>" -e "<typeinfo>" -e "<sstream>" -e "<type_traits>" -e "<memory>" -e "<regex>" \
+		-e "<tuple>" -e "<functional>" -e "<algorithm>" -e "<numeric>" -e "<locale>" -e "<map>" -e "<set>" -e "<unordered_map>" \
+		-e "<unordered_set>" -e "<iterator>" -e "<list>" -e "<deque>" -e "<stack>" -e "<queue>" -e "<array>" -e "<valarray>" \
+		-e "<bitset>" -e "<atomic>" > /dev/null; then \
+			echo "No disallowed headers found. All good!"; \
+		else \
+			echo "Disallowed headers found!" && exit 1; \
+		fi
+# Note Boost C++ has a collected header but for C++ STL ther is no such header so we must individually check for each header 
+
+# Clean up (make clean)
+clean: 
 	rm -f $(OBJS) $(TARGET)
